import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import Reveal from "./Reveal";

interface Piece {
  image: string;
  alt: string;
  title: string;
  detail: string;
  href?: string;
  linkLabel?: string;
}

const pieces: Piece[] = [
  {
    image: "/renders/saturno.webp",
    alt: "Saturn and its rings, rendered in-house.",
    title: "How Worlds Are Made",
    detail:
      "A YouTube channel of space documentaries where every scene is generated by code — no one ever opens the 3D software.",
    href: "https://www.youtube.com/@howworldsaremade",
    linkLabel: "visit channel",
  },
  {
    image: "/renders/cosmos.webp",
    alt: "A golden record drifting through deep space.",
    title: "94 minutes, zero hands",
    detail:
      "The flagship episode: researched, written, narrated, illustrated and cut by the pipeline — then published on schedule.",
    href: "https://youtu.be/QKI3rHDg9Wo",
    linkLabel: "watch",
  },
  {
    image: "/renders/lyrics.webp",
    alt: "Song lyrics floating over a calm simulated ocean.",
    title: "Words that make waves",
    detail:
      "Lyric videos where each sung word lands on a simulated ocean and leaves real ripples, in time with the voice.",
  },
];

export default function Studio() {
  return (
    <section id="studio" className="scroll-mt-24 border-t border-line bg-surface/40 px-6 py-28">
      <div className="mx-auto max-w-6xl">
        <Reveal>
          <p className="eyebrow mb-4">founder — verlet studio</p>
          <h2 className="display mb-6 max-w-3xl text-[clamp(2rem,5vw,3.6rem)]">
            A film studio made of code.
          </h2>
          <p className="mb-5 max-w-2xl text-lg leading-relaxed text-fog">
            Verlet makes deterministic 3D films of how real machines work —
            fusion devices, telescopes, tablet presses — built from published
            engineering models, with every figure on screen read off the
            geometry. Same scene in, same frames out, every time.
          </p>
          <p className="mb-14 max-w-2xl text-lg leading-relaxed text-fog">
            Everything below was rendered in-house: scenes described in code,
            lit and filmed by scripts, finished on my own GPU. Actual frames,
            not mockups.
          </p>
        </Reveal>

        <div className="grid gap-6 md:grid-cols-3">
          {pieces.map((piece, index) => (
            <Reveal key={piece.title} delay={index * 0.08}>
              <article className="group h-full overflow-hidden rounded-xl border border-line bg-panel transition-colors hover:border-amber/30">
                <div className="relative aspect-[16/9] overflow-hidden">
                  <Image
                    src={piece.image}
                    alt={piece.alt}
                    fill
                    className="object-cover transition-transform duration-700 group-hover:scale-[1.03]"
                    sizes="(max-width: 768px) 100vw, 33vw"
                  />
                </div>
                <div className="p-7">
                  <h3 className="mb-2.5 text-xl font-bold">{piece.title}</h3>
                  <p className="leading-relaxed text-fog">{piece.detail}</p>
                  {piece.href && (
                    <a
                      href={piece.href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="mt-4 inline-flex items-center gap-1.5 font-mono text-[0.8rem] text-amber transition-colors hover:text-paper"
                    >
                      {piece.linkLabel} <ArrowUpRight size={14} />
                    </a>
                  )}
                </div>
              </article>
            </Reveal>
          ))}
        </div>

        <Reveal delay={0.1}>
          <a
            href="https://verletstudio.com"
            target="_blank"
            rel="noopener noreferrer"
            className="group relative mt-10 inline-flex items-center gap-2 overflow-hidden rounded-lg border border-amber/40 bg-amber/10 px-7 py-3.5 font-medium text-amber transition-colors hover:bg-amber/20"
          >
            <span className="absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-white/10 to-transparent group-hover:animate-shimmer" />
            <span className="relative flex items-center gap-2">
              verletstudio.com <ArrowUpRight size={17} />
            </span>
          </a>
        </Reveal>
      </div>
    </section>
  );
}
